# Generated by Django 5.0.4 on 2024-05-10 12:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_finish', models.TimeField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('players_min', models.IntegerField()),
                ('players_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventsGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Games')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='limited_games',
            field=models.ManyToManyField(through='Events.EventsGames', to='Events.Games'),
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSign',
            fields=[
                ('sign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Events.sign')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.eventsgames')),
            ],
            bases=('Events.sign',),
        ),
    ]
