# Generated by Django 5.0.4 on 2024-05-10 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsgames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game'),
        ),
        migrations.AlterField(
            model_name='event',
            name='limited_games',
            field=models.ManyToManyField(through='Events.EventsGames', to='Games.game'),
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
