# Generated by Django 5.0.4 on 2024-05-10 13:56

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_game_sale_price'),
        ('Service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Games.comment', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.comment', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='complexity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Complexity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='equipment',
            field=models.TextField(verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='game',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Games.game', verbose_name='Expansion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_duration',
            field=models.IntegerField(verbose_name='Game Duration'),
        ),
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(to='Service.image', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.gamemaker', verbose_name='Maker'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_max',
            field=models.IntegerField(verbose_name='Maximum Players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_min',
            field=models.IntegerField(verbose_name='Minimum Players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.FileField(upload_to='rules/', verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='supposed_age',
            field=models.IntegerField(verbose_name='Supposed Age'),
        ),
        migrations.AlterField(
            model_name='gamemaker',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.comment', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
