# Generated by Django 5.0.4 on 2024-05-10 14:09

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_alter_category_name_alter_comment_date_and_more'),
        ('Service', '0002_alter_image_title_alter_video_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(verbose_name='Дата отзыва'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Games.comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.comment', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AlterField(
            model_name='game',
            name='complexity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Описание игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='equipment',
            field=models.TextField(verbose_name='Оборудование для игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Games.game', verbose_name='Расширение игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_duration',
            field=models.IntegerField(verbose_name='Продолжительность игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(to='Service.image', verbose_name='Изображения игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Логотип игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.gamemaker', verbose_name='Производитель игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_max',
            field=models.IntegerField(verbose_name='Максимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_min',
            field=models.IntegerField(verbose_name='Минимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.FileField(upload_to='rules/', verbose_name='Правила игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='URL-адрес игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='supposed_age',
            field=models.IntegerField(verbose_name='Рекомендуемый возраст для игры'),
        ),
        migrations.AlterField(
            model_name='gamemaker',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название производителя'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.comment', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='date',
            field=models.DateField(verbose_name='Дата отзыва'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг пользователя'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(to='Games.category', verbose_name='Категория игры'),
        ),
    ]
