# Generated by Django 5.0.4 on 2024-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_image_title_alter_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
