# Generated by Django 4.2.6 on 2023-11-05 11:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('places', models.IntegerField()),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='EventGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField()),
                ('current', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobby.event')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobby.event')),
                ('games', models.ManyToManyField(to='Hobby.eventgame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobby.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobby.game'),
        ),
        migrations.AddField(
            model_name='event',
            name='games',
            field=models.ManyToManyField(through='Hobby.EventGame', to='Hobby.game'),
        ),
    ]
