# Generated by Django 4.2.6 on 2023-10-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AlterField(
            model_name='eventgame',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
