# Generated by Django 4.2.6 on 2023-10-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hobby', '0002_remove_game_players_alter_eventgame_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_limited',
        ),
    ]
